"""Add profile_picture_url to User model

Revision ID: 456d7c46a813
Revises: 645097a61c9d
Create Date: 2025-07-24 01:27:16.017999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456d7c46a813'
down_revision = '645097a61c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture_url')

    # ### end Alembic commands ###
