"""Add community_id to Post model

Revision ID: 645097a61c9d
Revises: 17575db885dd
Create Date: 2025-07-23 23:41:37.870611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645097a61c9d'
down_revision = '17575db885dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.Integer(), nullable=True))
        # MODIFIED LINE: Added a name to the foreign key constraint
        batch_op.create_foreign_key('fk_post_community_id', 'community', ['community_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        # MODIFIED LINE: Specify the name of the foreign key constraint to drop
        batch_op.drop_constraint('fk_post_community_id', type_='foreignkey')
        batch_op.drop_column('community_id')

    # ### end Alembic commands ###