"""Add followed_type to Follow model

Revision ID: 94ba82c248c4
Revises: 456d7c46a813
Create Date: 2025-07-24 03:20:40.764894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ba82c248c4'
down_revision = '456d7c46a813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followed_type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_column('followed_type')

    # ### end Alembic commands ###
